name: Tests

on:
  push:
    branches:
      - cirq

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ok
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Test
        run: python -m pytest
